import { AlertsService } from './alerts.service';

describe('AlertsService', () => {
  beforeEach(() => {
    jest.clearAllMocks();
  });

  it('logs audit metadata when creating a manual alert', async () => {
    const prisma = {
      patient: { findUnique: jest.fn().mockResolvedValue({ id: 'pat-1', createdById: 'med-1', archivedAt: null, createdBy: null }) },
      clinicalAlert: {
        create: jest.fn().mockResolvedValue({
          id: 'alert-1',
          patientId: 'pat-1',
          encounterId: 'enc-1',
          type: 'GENERAL',
          severity: 'ALTA',
          title: 'Alerta',
          message: 'Mensaje',
          autoGenerated: false,
          createdById: 'med-1',
        }),
      },
      encounter: {
        findUnique: jest.fn().mockResolvedValue({ patientId: 'pat-1', medicoId: 'med-1' }),
      },
      user: { findMany: jest.fn() },
    };
    const audit = { log: jest.fn().mockResolvedValue(undefined) };
    const service = new AlertsService(prisma as never, audit as never);

    const result = await service.create(
      {
        patientId: 'pat-1',
        encounterId: 'enc-1',
        type: 'GENERAL',
        severity: 'ALTA',
        title: 'Alerta',
        message: 'Mensaje',
      },
      { id: 'med-1', role: 'MEDICO' },
    );

    expect(prisma.clinicalAlert.create).toHaveBeenCalled();
    expect(audit.log).toHaveBeenCalledWith(
      expect.objectContaining({
        entityType: 'ClinicalAlert',
        entityId: 'alert-1',
        reason: 'ALERT_CREATED',
      }),
    );
    expect(result.id).toBe('alert-1');
  });

  it('logs audit metadata when acknowledging an alert', async () => {
    const acknowledgedAt = new Date('2026-04-16T09:30:00.000Z');
    const prisma = {
      patient: { findUnique: jest.fn().mockResolvedValue({ id: 'pat-1', createdById: 'med-1', archivedAt: null, createdBy: null }) },
      clinicalAlert: {
        findUnique: jest.fn().mockResolvedValue({
          id: 'alert-1',
          patientId: 'pat-1',
          encounterId: 'enc-1',
          encounter: { medicoId: 'med-1' },
        }),
        update: jest.fn().mockResolvedValue({
          id: 'alert-1',
          acknowledgedAt,
          acknowledgedById: 'med-1',
        }),
      },
      user: { findMany: jest.fn() },
    };
    const audit = { log: jest.fn().mockResolvedValue(undefined) };
    const service = new AlertsService(prisma as never, audit as never);

    const result = await service.acknowledge('alert-1', { id: 'med-1', role: 'MEDICO' });

    expect(prisma.clinicalAlert.update).toHaveBeenCalled();
    expect(audit.log).toHaveBeenCalledWith(
      expect.objectContaining({
        entityType: 'ClinicalAlert',
        entityId: 'alert-1',
        reason: 'ALERT_ACKNOWLEDGED',
      }),
    );
    expect(result.acknowledgedById).toBe('med-1');
  });

  it('recreates an acknowledged auto-alert when the same critical value recurs', async () => {
    const prisma = {
      patient: { findUnique: jest.fn().mockResolvedValue({ id: 'pat-1', createdById: 'med-1', archivedAt: null, createdBy: null }) },
      clinicalAlert: {
        findFirst: jest.fn().mockResolvedValue({
          id: 'alert-1',
          acknowledgedAt: new Date('2026-04-16T08:00:00.000Z'),
        }),
        create: jest.fn().mockResolvedValue({
          id: 'alert-2',
          patientId: 'pat-1',
          encounterId: 'enc-1',
          type: 'SIGNOS_VITALES',
          severity: 'CRITICA',
          title: 'Alerta de signos vitales',
          message: 'Temperatura crítica: 39.6°C',
          autoGenerated: true,
          createdById: 'med-1',
        }),
      },
      encounter: { findUnique: jest.fn() },
      user: { findMany: jest.fn() },
    };
    const audit = { log: jest.fn().mockResolvedValue(undefined) };
    const service = new AlertsService(prisma as never, audit as never);

    const created = await service.checkVitalSigns(
      'pat-1',
      'enc-1',
      {
        temperatura: '39.6',
      },
      'med-1',
    );

    expect(created).toBe(1);
    expect(prisma.clinicalAlert.create).toHaveBeenCalledTimes(1);
    expect(audit.log).toHaveBeenCalledWith(
      expect.objectContaining({
        entityType: 'ClinicalAlert',
        entityId: 'alert-2',
        reason: 'ALERT_CREATED',
      }),
    );
  });
});