import { Injectable, NotFoundException, BadRequestException } from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';
import { AuditService } from '../audit/audit.service';
import { CreateAlertDto } from './dto/alert.dto';
import { getEffectiveMedicoId, RequestUser } from '../common/utils/medico-id';
import { assertPatientAccess, buildAccessiblePatientsWhere } from '../common/utils/patient-access';
import { getClinicalAlertMessages } from '../../../shared/vital-sign-alerts';

const ALERT_SEVERITY_WEIGHT: Record<string, number> = {
  CRITICA: 4,
  ALTA: 3,
  MEDIA: 2,
  BAJA: 1,
};

@Injectable()
export class AlertsService {
  constructor(
    private readonly prisma: PrismaService,
    private readonly audit: AuditService,
  ) {}

  private buildPatientLevelOwnershipWhere(effectiveMedicoId: string) {
    return {
      encounterId: null,
      OR: [
        { createdById: effectiveMedicoId },
        { createdBy: { medicoId: effectiveMedicoId } },
      ],
    };
  }

  private isPatientLevelAlertInMedicoScope(
    alert: { createdById: string; createdBy?: { medicoId: string | null } | null },
    effectiveMedicoId: string,
  ) {
    return alert.createdById === effectiveMedicoId || alert.createdBy?.medicoId === effectiveMedicoId;
  }

  private async assertEncounterMatchesPatient(encounterId: string, patientId: string, user: RequestUser) {
    const encounter = await this.prisma.encounter.findUnique({
      where: { id: encounterId },
      select: { patientId: true, medicoId: true },
    });

    if (!encounter) {
      throw new BadRequestException('La atención indicada no existe');
    }

    if (encounter.patientId !== patientId) {
      throw new BadRequestException('La atención indicada no corresponde al paciente');
    }

    if (!user.isAdmin && encounter.medicoId !== getEffectiveMedicoId(user)) {
      throw new BadRequestException('La atención indicada no existe para este paciente');
    }
  }

  private sortAlertsByPriority<T extends { severity: string; createdAt: Date }>(alerts: T[]) {
    return [...alerts].sort((left, right) => {
      const severityDelta = (ALERT_SEVERITY_WEIGHT[right.severity] || 0) - (ALERT_SEVERITY_WEIGHT[left.severity] || 0);
      if (severityDelta !== 0) {
        return severityDelta;
      }

      return right.createdAt.getTime() - left.createdAt.getTime();
    });
  }

  private async attachUserNames<
    T extends {
      createdById: string;
      acknowledgedById?: string | null;
    },
  >(alerts: T[]) {
    const userIds = Array.from(
      new Set(
        alerts
          .flatMap((alert) => [alert.createdById, alert.acknowledgedById])
          .filter((value): value is string => Boolean(value)),
      ),
    );

    if (userIds.length === 0) {
      return alerts.map((alert) => ({
        ...alert,
        createdBy: null,
        acknowledgedBy: null,
      }));
    }

    const users = await this.prisma.user.findMany({
      where: { id: { in: userIds } },
      select: { id: true, nombre: true },
    });
    const userMap = new Map(users.map((user) => [user.id, user]));

    return alerts.map((alert) => ({
      ...alert,
      createdBy: userMap.get(alert.createdById) || null,
      acknowledgedBy: alert.acknowledgedById ? userMap.get(alert.acknowledgedById) || null : null,
    }));
  }

  async create(dto: CreateAlertDto, user: RequestUser) {
    await assertPatientAccess(this.prisma, user, dto.patientId);

    if (dto.encounterId) {
      await this.assertEncounterMatchesPatient(dto.encounterId, dto.patientId, user);
    }

    const alert = await this.prisma.clinicalAlert.create({
      data: {
        patientId: dto.patientId,
        encounterId: dto.encounterId ?? null,
        type: dto.type,
        severity: dto.severity,
        title: dto.title,
        message: dto.message,
        createdById: user.id,
      },
    });

    await this.audit.log({
      entityType: 'ClinicalAlert',
      entityId: alert.id,
      userId: user.id,
      action: 'CREATE',
      reason: 'ALERT_CREATED',
      diff: {
        patientId: alert.patientId,
        encounterId: alert.encounterId,
        type: alert.type,
        severity: alert.severity,
        title: alert.title,
        autoGenerated: alert.autoGenerated,
      },
    });

    return alert;
  }

  async findByPatient(patientId: string, user: RequestUser, includeAcknowledged = false) {
    await assertPatientAccess(this.prisma, user, patientId);

    const effectiveMedicoId = user.isAdmin ? null : getEffectiveMedicoId(user);
    const alerts = await this.prisma.clinicalAlert.findMany({
      where: {
        patientId,
        ...(includeAcknowledged ? {} : { acknowledgedAt: null }),
        ...(effectiveMedicoId
          ? {
              OR: [
                this.buildPatientLevelOwnershipWhere(effectiveMedicoId),
                { encounter: { medicoId: effectiveMedicoId } },
              ],
            }
          : {}),
      },
    });

    const sortedAlerts = this.sortAlertsByPriority(alerts);
    return this.attachUserNames(sortedAlerts);
  }

  async acknowledge(id: string, user: RequestUser) {
    const effectiveMedicoId = user.isAdmin ? null : getEffectiveMedicoId(user);
    const alert = await this.prisma.clinicalAlert.findUnique({
      where: { id },
      include: {
        encounter: {
          select: { medicoId: true },
        },
        createdBy: {
          select: { medicoId: true },
        },
      },
    });
    if (!alert) throw new NotFoundException('Alerta no encontrada');

    await assertPatientAccess(this.prisma, user, alert.patientId);

    if (!user.isAdmin && effectiveMedicoId) {
      if (alert.encounterId) {
        if (alert.encounter?.medicoId !== effectiveMedicoId) {
          throw new NotFoundException('Alerta no encontrada');
        }
      } else if (!this.isPatientLevelAlertInMedicoScope(alert, effectiveMedicoId)) {
        throw new NotFoundException('Alerta no encontrada');
      }
    }

    if (alert.acknowledgedAt) {
      return alert;
    }

    const updated = await this.prisma.clinicalAlert.update({
      where: { id },
      data: {
        acknowledgedAt: new Date(),
        acknowledgedById: user.id,
      },
    });

    await this.audit.log({
      entityType: 'ClinicalAlert',
      entityId: updated.id,
      userId: user.id,
      action: 'UPDATE',
      reason: 'ALERT_ACKNOWLEDGED',
      diff: {
        acknowledgedAt: updated.acknowledgedAt,
        acknowledgedById: updated.acknowledgedById,
      },
    });

    return updated;
  }

  /** Auto-generate alerts from vital signs in encounter sections */
  async checkVitalSigns(patientId: string, encounterId: string, vitals: Record<string, string>, userId: string) {
    const alerts = getClinicalAlertMessages(vitals);

    let createdAlerts = 0;

    for (const message of alerts) {
      const existingAlert = await this.prisma.clinicalAlert.findFirst({
        where: {
          patientId,
          encounterId,
          type: 'SIGNOS_VITALES',
          severity: 'CRITICA',
          title: 'Alerta de signos vitales',
          message,
          autoGenerated: true,
        },
        select: { id: true, acknowledgedAt: true },
      });

      if (existingAlert && !existingAlert.acknowledgedAt) {
        continue;
      }

      const createdAlert = await this.prisma.clinicalAlert.create({
        data: {
          patientId,
          encounterId,
          type: 'SIGNOS_VITALES',
          severity: 'CRITICA',
          title: 'Alerta de signos vitales',
          message,
          autoGenerated: true,
          createdById: userId,
        },
      });

      await this.audit.log({
        entityType: 'ClinicalAlert',
        entityId: createdAlert.id,
        userId,
        action: 'CREATE',
        reason: 'ALERT_CREATED',
        diff: {
          patientId: createdAlert.patientId,
          encounterId: createdAlert.encounterId,
          type: createdAlert.type,
          severity: createdAlert.severity,
          title: createdAlert.title,
          autoGenerated: createdAlert.autoGenerated,
        },
      });

      createdAlerts += 1;
    }

    return createdAlerts;
  }

  async countUnacknowledged(user: RequestUser): Promise<number> {
    const patientWhere = buildAccessiblePatientsWhere(user);
    const effectiveMedicoId = user.isAdmin ? null : getEffectiveMedicoId(user);

    return this.prisma.clinicalAlert.count({
      where: {
        acknowledgedAt: null,
        ...(effectiveMedicoId
          ? {
              OR: [
                {
                  ...this.buildPatientLevelOwnershipWhere(effectiveMedicoId),
                  patient: patientWhere,
                },
                {
                  encounter: {
                    medicoId: effectiveMedicoId,
                    patient: { archivedAt: null },
                  },
                },
              ],
            }
          : {
              patient: patientWhere,
            }),
      },
    });
  }

  async findRecentUnacknowledged(user: RequestUser, take = 10) {
    const patientWhere = buildAccessiblePatientsWhere(user);
    const effectiveMedicoId = user.isAdmin ? null : getEffectiveMedicoId(user);

    const alerts = await this.prisma.clinicalAlert.findMany({
      where: {
        acknowledgedAt: null,
        ...(effectiveMedicoId
          ? {
              OR: [
                {
                  ...this.buildPatientLevelOwnershipWhere(effectiveMedicoId),
                  patient: patientWhere,
                },
                {
                  encounter: {
                    medicoId: effectiveMedicoId,
                    patient: { archivedAt: null },
                  },
                },
              ],
            }
          : {
              patient: patientWhere,
            }),
      },
      select: {
        id: true,
        type: true,
        severity: true,
        title: true,
        message: true,
        createdAt: true,
        patient: {
          select: { id: true, nombre: true },
        },
      },
    });

    return this.sortAlertsByPriority(alerts).slice(0, take);
  }
}
