import { Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';
import { AuditService } from '../audit/audit.service';
import { CreateAlertDto } from './dto/alert.dto';
import { getEffectiveMedicoId, RequestUser } from '../common/utils/medico-id';
import { assertPatientAccess } from '../common/utils/patient-access';
import { getClinicalAlertMessages } from '../../../shared/vital-sign-alerts';
import {
  assertEncounterMatchesPatient,
  attachUserNames,
  buildPatientLevelOwnershipWhere,
  isPatientLevelAlertInMedicoScope,
  sortAlertsByPriority,
} from './alerts.service.helpers';
import {
  countUnacknowledgedAlerts,
  findRecentUnacknowledgedAlerts,
} from './alerts.service.metrics';

@Injectable()
export class AlertsService {
  constructor(
    private readonly prisma: PrismaService,
    private readonly audit: AuditService,
  ) {}

  async create(dto: CreateAlertDto, user: RequestUser) {
    await assertPatientAccess(this.prisma, user, dto.patientId);

    if (dto.encounterId) {
      await assertEncounterMatchesPatient(this.prisma, dto.encounterId, dto.patientId, user);
    }

    const alert = await this.prisma.clinicalAlert.create({
      data: {
        patientId: dto.patientId,
        encounterId: dto.encounterId ?? null,
        type: dto.type,
        severity: dto.severity,
        title: dto.title,
        message: dto.message,
        createdById: user.id,
      },
    });

    await this.audit.log({
      entityType: 'ClinicalAlert',
      entityId: alert.id,
      userId: user.id,
      action: 'CREATE',
      reason: 'ALERT_CREATED',
      diff: {
        patientId: alert.patientId,
        encounterId: alert.encounterId,
        type: alert.type,
        severity: alert.severity,
        title: alert.title,
        autoGenerated: alert.autoGenerated,
      },
    });

    return alert;
  }

  async findByPatient(
    patientId: string,
    user: RequestUser,
    options: { includeAcknowledged?: boolean; acknowledgedLimit?: number; withMeta: true },
  ): Promise<{ data: any[]; meta: { acknowledgedHasMore: boolean } }>;
  async findByPatient(
    patientId: string,
    user: RequestUser,
    options?: { includeAcknowledged?: boolean; acknowledgedLimit?: number; withMeta?: false },
  ): Promise<any[]>;
  async findByPatient(
    patientId: string,
    user: RequestUser,
    options: { includeAcknowledged?: boolean; acknowledgedLimit?: number; withMeta?: boolean } = {},
  ): Promise<any[] | { data: any[]; meta: { acknowledgedHasMore: boolean } }> {
    await assertPatientAccess(this.prisma, user, patientId);

    const effectiveMedicoId = user.isAdmin ? null : getEffectiveMedicoId(user);
    const scopeWhere = {
      patientId,
      ...(effectiveMedicoId
        ? {
            OR: [
              buildPatientLevelOwnershipWhere(effectiveMedicoId),
              { encounter: { medicoId: effectiveMedicoId } },
            ],
          }
        : {}),
    };

    const activeAlerts = await this.prisma.clinicalAlert.findMany({
      where: {
        ...scopeWhere,
        acknowledgedAt: null,
      },
    });

    const acknowledgedLimit = Number.isFinite(options.acknowledgedLimit)
      ? Math.max(0, Math.min(options.acknowledgedLimit ?? 0, 100))
      : undefined;
    const acknowledgedTake =
      options.withMeta && acknowledgedLimit !== undefined ? acknowledgedLimit + 1 : acknowledgedLimit;
    const rawAcknowledgedAlerts = options.includeAcknowledged
      ? await this.prisma.clinicalAlert.findMany({
          where: {
            ...scopeWhere,
            acknowledgedAt: { not: null },
          },
          orderBy: { acknowledgedAt: 'desc' },
          ...(acknowledgedTake === undefined ? {} : { take: acknowledgedTake }),
        })
      : [];
    const acknowledgedHasMore = acknowledgedLimit !== undefined && rawAcknowledgedAlerts.length > acknowledgedLimit;
    const acknowledgedAlerts = acknowledgedHasMore
      ? rawAcknowledgedAlerts.slice(0, acknowledgedLimit)
      : rawAcknowledgedAlerts;

    const sortedAlerts = [
      ...sortAlertsByPriority(activeAlerts),
      ...acknowledgedAlerts,
    ];
    const alerts = await attachUserNames(this.prisma, sortedAlerts);
    if (options.withMeta) {
      return {
        data: alerts,
        meta: {
          acknowledgedHasMore,
        },
      };
    }
    return alerts;
  }

  async acknowledge(id: string, user: RequestUser) {
    const effectiveMedicoId = user.isAdmin ? null : getEffectiveMedicoId(user);
    const alert = await this.prisma.clinicalAlert.findUnique({
      where: { id },
      include: {
        encounter: {
          select: { medicoId: true },
        },
        createdBy: {
          select: { medicoId: true },
        },
      },
    });
    if (!alert) throw new NotFoundException('Alerta no encontrada');

    await assertPatientAccess(this.prisma, user, alert.patientId);

    if (!user.isAdmin && effectiveMedicoId) {
      if (alert.encounterId) {
        if (alert.encounter?.medicoId !== effectiveMedicoId) {
          throw new NotFoundException('Alerta no encontrada');
        }
      } else if (!isPatientLevelAlertInMedicoScope(alert, effectiveMedicoId)) {
        throw new NotFoundException('Alerta no encontrada');
      }
    }

    if (alert.acknowledgedAt) {
      return alert;
    }

    const updated = await this.prisma.clinicalAlert.update({
      where: { id },
      data: {
        acknowledgedAt: new Date(),
        acknowledgedById: user.id,
      },
    });

    await this.audit.log({
      entityType: 'ClinicalAlert',
      entityId: updated.id,
      userId: user.id,
      action: 'UPDATE',
      reason: 'ALERT_ACKNOWLEDGED',
      diff: {
        acknowledgedAt: updated.acknowledgedAt,
        acknowledgedById: updated.acknowledgedById,
      },
    });

    return updated;
  }

  /** Auto-generate alerts from vital signs in encounter sections */
  async checkVitalSigns(patientId: string, encounterId: string, vitals: Record<string, string>, userId: string) {
    const alerts = getClinicalAlertMessages(vitals);

    let createdAlerts = 0;

    for (const message of alerts) {
      const existingAlert = await this.prisma.clinicalAlert.findFirst({
        where: {
          patientId,
          encounterId,
          type: 'SIGNOS_VITALES',
          severity: 'CRITICA',
          title: 'Alerta de signos vitales',
          message,
          autoGenerated: true,
        },
        select: { id: true, acknowledgedAt: true },
      });

      if (existingAlert && !existingAlert.acknowledgedAt) {
        continue;
      }

      const createdAlert = await this.prisma.clinicalAlert.create({
        data: {
          patientId,
          encounterId,
          type: 'SIGNOS_VITALES',
          severity: 'CRITICA',
          title: 'Alerta de signos vitales',
          message,
          autoGenerated: true,
          createdById: userId,
        },
      });

      await this.audit.log({
        entityType: 'ClinicalAlert',
        entityId: createdAlert.id,
        userId,
        action: 'CREATE',
        reason: 'ALERT_CREATED',
        diff: {
          patientId: createdAlert.patientId,
          encounterId: createdAlert.encounterId,
          type: createdAlert.type,
          severity: createdAlert.severity,
          title: createdAlert.title,
          autoGenerated: createdAlert.autoGenerated,
        },
      });

      createdAlerts += 1;
    }

    return createdAlerts;
  }

  async countUnacknowledged(user: RequestUser): Promise<number> {
    return countUnacknowledgedAlerts(this.prisma, user);
  }

  async findRecentUnacknowledged(user: RequestUser, take = 10) {
    const alerts = await findRecentUnacknowledgedAlerts(this.prisma, user, take);
    return sortAlertsByPriority(alerts).slice(0, take);
  }
}
