import { SectionKey } from '../types';
import {
  ENCOUNTER_SECTION_SCHEMA_REGISTRY,
  getEncounterSectionSchemaVersion,
} from './encounter-section-schema';

export const ENCOUNTER_SECTION_ORDER: SectionKey[] = [
  'IDENTIFICACION',
  'MOTIVO_CONSULTA',
  'ANAMNESIS_PROXIMA',
  'ANAMNESIS_REMOTA',
  'REVISION_SISTEMAS',
  'EXAMEN_FISICO',
  'SOSPECHA_DIAGNOSTICA',
  'TRATAMIENTO',
  'RESPUESTA_TRATAMIENTO',
  'OBSERVACIONES',
];

export const ENCOUNTER_SECTION_LABELS: Record<SectionKey, string> = {
  IDENTIFICACION: 'Identificación del paciente',
  MOTIVO_CONSULTA: 'Motivo de consulta',
  ANAMNESIS_PROXIMA: 'Anamnesis próxima',
  ANAMNESIS_REMOTA: 'Anamnesis remota',
  REVISION_SISTEMAS: 'Revisión por sistemas',
  EXAMEN_FISICO: 'Examen físico',
  SOSPECHA_DIAGNOSTICA: 'Sospecha diagnóstica',
  TRATAMIENTO: 'Tratamiento',
  RESPUESTA_TRATAMIENTO: 'Respuesta al tratamiento',
  OBSERVACIONES: 'Observaciones',
};

export const ENCOUNTER_SECTION_SCHEMA_VERSIONS: Record<SectionKey, number> = {
  IDENTIFICACION: ENCOUNTER_SECTION_SCHEMA_REGISTRY.IDENTIFICACION.currentVersion,
  MOTIVO_CONSULTA: ENCOUNTER_SECTION_SCHEMA_REGISTRY.MOTIVO_CONSULTA.currentVersion,
  ANAMNESIS_PROXIMA: ENCOUNTER_SECTION_SCHEMA_REGISTRY.ANAMNESIS_PROXIMA.currentVersion,
  ANAMNESIS_REMOTA: ENCOUNTER_SECTION_SCHEMA_REGISTRY.ANAMNESIS_REMOTA.currentVersion,
  REVISION_SISTEMAS: ENCOUNTER_SECTION_SCHEMA_REGISTRY.REVISION_SISTEMAS.currentVersion,
  EXAMEN_FISICO: ENCOUNTER_SECTION_SCHEMA_REGISTRY.EXAMEN_FISICO.currentVersion,
  SOSPECHA_DIAGNOSTICA: ENCOUNTER_SECTION_SCHEMA_REGISTRY.SOSPECHA_DIAGNOSTICA.currentVersion,
  TRATAMIENTO: ENCOUNTER_SECTION_SCHEMA_REGISTRY.TRATAMIENTO.currentVersion,
  RESPUESTA_TRATAMIENTO: ENCOUNTER_SECTION_SCHEMA_REGISTRY.RESPUESTA_TRATAMIENTO.currentVersion,
  OBSERVACIONES: ENCOUNTER_SECTION_SCHEMA_REGISTRY.OBSERVACIONES.currentVersion,
};

export { getEncounterSectionSchemaVersion };
