export const PATIENT_NAME_MIN_LENGTH = 2;
export const PATIENT_NAME_MAX_LENGTH = 200;
export const PATIENT_RUT_MAX_LENGTH = 20;
export const PATIENT_RUT_EXEMPT_REASON_MAX_LENGTH = 500;
export const PATIENT_JOB_MAX_LENGTH = 200;
export const PATIENT_ADDRESS_MAX_LENGTH = 500;
export const PATIENT_MEDICAL_CENTER_MAX_LENGTH = 200;
