// Local type definitions for SQLite compatibility
// SQLite doesn't support ENUMs, so we define them as string literal types

export type Role = 'MEDICO' | 'ASISTENTE' | 'ADMIN';

export type Sexo = 'MASCULINO' | 'FEMENINO' | 'OTRO' | 'PREFIERE_NO_DECIR';

export type Prevision = 'FONASA' | 'ISAPRE' | 'OTRA' | 'DESCONOCIDA';
export type PatientRegistrationMode = 'COMPLETO' | 'RAPIDO';
export type PatientCompletenessStatus = 'INCOMPLETA' | 'PENDIENTE_VERIFICACION' | 'VERIFICADA';

export type EncounterStatus = 'EN_PROGRESO' | 'COMPLETADO' | 'CANCELADO';
export type EncounterReviewStatus =
  | 'NO_REQUIERE_REVISION'
  | 'LISTA_PARA_REVISION'
  | 'REVISADA_POR_MEDICO';

export type SectionKey = 
  | 'IDENTIFICACION'
  | 'MOTIVO_CONSULTA'
  | 'ANAMNESIS_PROXIMA'
  | 'ANAMNESIS_REMOTA'
  | 'REVISION_SISTEMAS'
  | 'EXAMEN_FISICO'
  | 'SOSPECHA_DIAGNOSTICA'
  | 'TRATAMIENTO'
  | 'RESPUESTA_TRATAMIENTO'
  | 'OBSERVACIONES';

export type ChosenMode = 'AUTO' | 'MANUAL';

export type AuditAction =
  | 'CREATE'
  | 'UPDATE'
  | 'DELETE'
  | 'LOGIN'
  | 'LOGOUT'
  | 'LOGIN_FAILED'
  | 'PASSWORD_CHANGED'
  | 'EXPORT'
  | 'DOWNLOAD';
export type AuditResult = 'SUCCESS' | 'REJECTED' | 'ERROR';
export type AuditReason =
  | 'AUTH_LOGIN'
  | 'AUTH_LOGOUT'
  | 'AUTH_LOGIN_REJECTED'
  | 'AUTH_2FA_ENABLED'
  | 'AUTH_2FA_DISABLED'
  | 'PATIENT_CREATED'
  | 'PATIENT_HISTORY_CREATED'
  | 'PATIENT_UPDATED'
  | 'PATIENT_ADMIN_UPDATED'
  | 'PATIENT_HISTORY_UPDATED'
  | 'PATIENT_PROBLEM_CREATED'
  | 'PATIENT_PROBLEM_UPDATED'
  | 'PATIENT_TASK_CREATED'
  | 'PATIENT_TASK_UPDATED'
  | 'PATIENT_ARCHIVED'
  | 'PATIENT_RESTORED'
  | 'PATIENT_EXPORT_CSV'
  | 'ENCOUNTER_CREATED'
  | 'ENCOUNTER_SECTION_UPDATED'
  | 'ENCOUNTER_COMPLETED'
  | 'ENCOUNTER_REOPENED'
  | 'ENCOUNTER_CANCELLED'
  | 'ENCOUNTER_REVIEW_STATUS_UPDATED'
  | 'ENCOUNTER_DOCUMENT_EXPORTED'
  | 'ATTACHMENT_UPLOADED'
  | 'ATTACHMENT_DOWNLOADED'
  | 'ATTACHMENT_DELETED'
  | 'CONSENT_GRANTED'
  | 'CONSENT_REVOKED'
  | 'USER_INVITATION_CREATED'
  | 'USER_INVITATION_REVOKED'
  | 'USER_UPDATED'
  | 'USER_DEACTIVATED'
  | 'USER_PROFILE_UPDATED'
  | 'USER_PASSWORD_CHANGED'
  | 'USER_PASSWORD_RESET'
  | 'SETTINGS_UPDATED'
  | 'AUDIT_UNSPECIFIED';
export type PatientProblemStatus = 'ACTIVO' | 'CRONICO' | 'EN_ESTUDIO' | 'RESUELTO';
export type EncounterTaskStatus = 'PENDIENTE' | 'EN_PROCESO' | 'COMPLETADA' | 'CANCELADA';
export type EncounterTaskType = 'SEGUIMIENTO' | 'EXAMEN' | 'DERIVACION' | 'TRAMITE';
export type EncounterTaskPriority = 'ALTA' | 'MEDIA' | 'BAJA';

// Enum values arrays for validation
export const ROLES = ['MEDICO', 'ASISTENTE', 'ADMIN'] as const;
export const SEXOS = ['MASCULINO', 'FEMENINO', 'OTRO', 'PREFIERE_NO_DECIR'] as const;
export const PREVISIONES = ['FONASA', 'ISAPRE', 'OTRA', 'DESCONOCIDA'] as const;
export const PATIENT_REGISTRATION_MODES = ['COMPLETO', 'RAPIDO'] as const;
export const PATIENT_COMPLETENESS_STATUSES = [
  'INCOMPLETA',
  'PENDIENTE_VERIFICACION',
  'VERIFICADA',
] as const;
export const ENCOUNTER_STATUSES = ['EN_PROGRESO', 'COMPLETADO', 'FIRMADO', 'CANCELADO'] as const;
export const ENCOUNTER_REVIEW_STATUSES = [
  'NO_REQUIERE_REVISION',
  'LISTA_PARA_REVISION',
  'REVISADA_POR_MEDICO',
] as const;
export const SECTION_KEYS = [
  'IDENTIFICACION',
  'MOTIVO_CONSULTA',
  'ANAMNESIS_PROXIMA',
  'ANAMNESIS_REMOTA',
  'REVISION_SISTEMAS',
  'EXAMEN_FISICO',
  'SOSPECHA_DIAGNOSTICA',
  'TRATAMIENTO',
  'RESPUESTA_TRATAMIENTO',
  'OBSERVACIONES',
] as const;
export const CHOSEN_MODES = ['AUTO', 'MANUAL'] as const;
export const AUDIT_ACTIONS = [
  'CREATE',
  'UPDATE',
  'DELETE',
  'LOGIN',
  'LOGOUT',
  'LOGIN_FAILED',
  'PASSWORD_CHANGED',
  'EXPORT',
  'DOWNLOAD',
] as const;
export const AUDIT_RESULTS = ['SUCCESS', 'REJECTED', 'ERROR'] as const;
export const PATIENT_PROBLEM_STATUSES = ['ACTIVO', 'CRONICO', 'EN_ESTUDIO', 'RESUELTO'] as const;
export const ENCOUNTER_TASK_STATUSES = ['PENDIENTE', 'EN_PROCESO', 'COMPLETADA', 'CANCELADA'] as const;
export const ENCOUNTER_TASK_TYPES = ['SEGUIMIENTO', 'EXAMEN', 'DERIVACION', 'TRAMITE'] as const;
export const ENCOUNTER_TASK_PRIORITIES = ['ALTA', 'MEDIA', 'BAJA'] as const;
