// Local domain type definitions mirrored from Prisma string fields.
// Postgres native enums are intentionally deferred to a later model refactor.

export type Role = 'MEDICO' | 'ASISTENTE' | 'ADMIN';

export type Sexo = 'MASCULINO' | 'FEMENINO' | 'OTRO' | 'PREFIERE_NO_DECIR';

export type Prevision = 'FONASA' | 'ISAPRE' | 'OTRA' | 'DESCONOCIDA';
export type PatientRegistrationMode = 'COMPLETO' | 'RAPIDO';
export type PatientCompletenessStatus = 'INCOMPLETA' | 'PENDIENTE_VERIFICACION' | 'VERIFICADA';

export type EncounterStatus = 'EN_PROGRESO' | 'COMPLETADO' | 'FIRMADO' | 'CANCELADO';
export type EncounterReviewStatus =
  | 'NO_REQUIERE_REVISION'
  | 'LISTA_PARA_REVISION'
  | 'REVISADA_POR_MEDICO';

export type SectionKey = 
  | 'IDENTIFICACION'
  | 'MOTIVO_CONSULTA'
  | 'ANAMNESIS_PROXIMA'
  | 'ANAMNESIS_REMOTA'
  | 'REVISION_SISTEMAS'
  | 'EXAMEN_FISICO'
  | 'SOSPECHA_DIAGNOSTICA'
  | 'TRATAMIENTO'
  | 'RESPUESTA_TRATAMIENTO'
  | 'OBSERVACIONES';

export type ChosenMode = 'AUTO' | 'MANUAL';

export type AuditAction =
  | 'CREATE'
  | 'UPDATE'
  | 'DELETE'
  | 'SOFT_DELETE'
  | 'LOGIN'
  | 'LOGOUT'
  | 'LOGIN_FAILED'
  | 'PASSWORD_CHANGED'
  | 'READ'
  | 'EXPORT'
  | 'DOWNLOAD';
export type AuditResult = 'SUCCESS' | 'REJECTED' | 'ERROR';
export type AuditReason =
  | 'AUTH_LOGIN'
  | 'AUTH_LOGOUT'
  | 'AUTH_LOGIN_REJECTED'
  | 'AUTH_2FA_ENABLED'
  | 'AUTH_2FA_DISABLED'
  | 'AUTH_2FA_RECOVERY_CODES_REGENERATED'
  | 'PATIENT_CREATED'
  | 'PATIENT_HISTORY_CREATED'
  | 'PATIENT_UPDATED'
  | 'PATIENT_ADMIN_UPDATED'
  | 'PATIENT_HISTORY_UPDATED'
  | 'PATIENT_PROBLEM_CREATED'
  | 'PATIENT_PROBLEM_UPDATED'
  | 'PATIENT_TASK_CREATED'
  | 'PATIENT_TASK_UPDATED'
  | 'PATIENT_ARCHIVED'
  | 'PATIENT_RESTORED'
  | 'PATIENT_REASSIGNED'
  | 'PATIENT_RECORD_VIEWED'
  | 'PATIENT_CLINICAL_SUMMARY_VIEWED'
  | 'PATIENT_LIST_VIEWED'
  | 'PATIENT_DUPLICATES_SEARCHED'
  | 'PATIENT_ADMIN_SUMMARY_VIEWED'
  | 'PATIENT_TIMELINE_VIEWED'
  | 'PATIENT_OPERATIONAL_HISTORY_VIEWED'
  | 'PATIENT_TASKS_VIEWED'
  | 'PATIENT_EXPORT_CSV'
  | 'PATIENT_LONGITUDINAL_EXPORTED'
  | 'PATIENT_BUNDLE_EXPORTED'
  | 'CLINICAL_ANALYTICS_CSV_EXPORTED'
  | 'CLINICAL_ANALYTICS_SUMMARY_VIEWED'
  | 'CLINICAL_ANALYTICS_CASES_VIEWED'
  | 'CLINICAL_ANALYTICS_SUMMARY_CSV_EXPORTED'
  | 'CLINICAL_ANALYTICS_SUMMARY_REPORT_EXPORTED'
  | 'ENCOUNTER_CREATED'
  | 'ENCOUNTER_SECTION_UPDATED'
  | 'ENCOUNTER_COMPLETED'
  | 'ENCOUNTER_SIGNED'
  | 'ENCOUNTER_REOPENED'
  | 'ENCOUNTER_CANCELLED'
  | 'ENCOUNTER_REVIEW_STATUS_UPDATED'
  | 'ENCOUNTER_REASSIGNED'
  | 'ENCOUNTER_RECORD_VIEWED'
  | 'ENCOUNTER_TIMELINE_VIEWED'
  | 'ENCOUNTER_DOCUMENT_EXPORTED'
  | 'ATTACHMENT_UPLOADED'
  | 'ATTACHMENT_LIST_VIEWED'
  | 'ATTACHMENT_DOWNLOADED'
  | 'ATTACHMENT_DELETED'
  | 'ATTACHMENT_SOFT_DELETED'
  | 'ALERT_CREATED'
  | 'ALERT_LIST_VIEWED'
  | 'ALERT_ACKNOWLEDGED'
  | 'CONSENT_LIST_VIEWED'
  | 'CONSENT_GRANTED'
  | 'CONSENT_REVOKED'
  | 'USER_INVITATION_CREATED'
  | 'USER_INVITATION_REVOKED'
  | 'USER_UPDATED'
  | 'USER_DEACTIVATED'
  | 'USER_PROFILE_UPDATED'
  | 'USER_PASSWORD_CHANGED'
  | 'USER_PASSWORD_RESET'
  | 'USER_PASSWORD_RESET_REQUESTED'
  | 'USER_PASSWORD_RESET_VIA_EMAIL'
  | 'PATIENT_DATA_EXPORTED_REGULATORY'
  | 'PATIENT_RECORD_PURGED_REGULATORY'
  | 'ATTACHMENT_QUARANTINED'
  | 'TEXT_TEMPLATE_CREATED'
  | 'TEXT_TEMPLATE_UPDATED'
  | 'TEXT_TEMPLATE_DELETED'
  | 'CONDITION_CSV_IMPORTED'
  | 'MEDICATION_CSV_IMPORTED'
  | 'SETTINGS_UPDATED'
  | 'ADMIN_MAINTENANCE_EXECUTED'
  | 'AUDIT_EMERGENCY_EVENT'
  // Ley 21.719 - consentimiento del titular (Art 12)
  | 'PATIENT_DATA_CONSENT_GRANTED'
  | 'PATIENT_DATA_CONSENT_REVOKED'
  | 'PATIENT_DATA_CONSENT_LIST_VIEWED'
  // Ley 21.719 - derechos del titular (Art 4-11)
  | 'PATIENT_RIGHT_REQUESTED'
  | 'PATIENT_RIGHT_RESOLVED_ACCEPTED'
  | 'PATIENT_RIGHT_RESOLVED_REJECTED'
  | 'PATIENT_RIGHT_EXPIRED'
  | 'PATIENT_RIGHT_LIST_VIEWED'
  | 'PATIENT_RIGHT_VIEWED'
  | 'PATIENT_RIGHT_ADMIN_UPDATED'
  | 'PATIENT_RIGHT_EXTENDED'
  | 'PATIENT_DATA_REQUEST_EXPORT_LINK_CREATED'
  | 'PATIENT_DATA_REQUEST_EXPORT_DOWNLOADED'
  | 'PATIENT_DATA_REQUEST_EXPORT_EXPIRED'
  | 'PATIENT_DATA_REQUEST_EXPORT_REVOKED'
  // Ley 21.719 - bloqueo temporal (Art 8 ter)
  | 'PATIENT_BLOCKED'
  | 'PATIENT_UNBLOCKED'
  | 'PATIENT_PORTAL_LOGIN'
  | 'PATIENT_PORTAL_RECORD_VIEWED'
  | 'PATIENT_PORTAL_ENCOUNTER_VIEWED'
  | 'PATIENT_PORTAL_DOCUMENT_DOWNLOADED'
  | 'PATIENT_PORTAL_DATA_REQUEST_CREATED'
  // Ley 21.719 - brechas (Art 14 sexies)
  | 'DATA_BREACH_DETECTED'
  | 'DATA_BREACH_ASSESSED'
  | 'DATA_BREACH_REPORTED_TO_AGENCY'
  | 'DATA_BREACH_NOTIFIED_TO_SUBJECTS'
  | 'DATA_BREACH_CLOSED'
  | 'DATA_BREACH_LIST_VIEWED'
  | 'DATA_BREACH_VIEWED'
  | 'ALLERGY_CREATED'
  | 'ALLERGY_UPDATED'
  | 'ALLERGY_REMOVED'
  | 'MEDICATION_CREATED'
  | 'MEDICATION_UPDATED'
  | 'MEDICATION_REMOVED'
  | 'APPOINTMENT_CREATED'
  | 'APPOINTMENT_UPDATED'
  | 'APPOINTMENT_CANCELLED'
  | 'AUDIT_UNSPECIFIED';
export type PatientProblemStatus = 'ACTIVO' | 'CRONICO' | 'EN_ESTUDIO' | 'RESUELTO';
export type EncounterTaskStatus = 'PENDIENTE' | 'EN_PROCESO' | 'COMPLETADA' | 'CANCELADA';
export type EncounterTaskType = 'SEGUIMIENTO' | 'EXAMEN' | 'DERIVACION' | 'TRAMITE';
export type EncounterTaskPriority = 'ALTA' | 'MEDIA' | 'BAJA';
export type EncounterTaskRecurrenceRule = 'NONE' | 'WEEKLY' | 'MONTHLY';

// Enum values arrays for validation
export const ROLES = ['MEDICO', 'ASISTENTE', 'ADMIN'] as const;
export const SEXOS = ['MASCULINO', 'FEMENINO', 'OTRO', 'PREFIERE_NO_DECIR'] as const;
export const PREVISIONES = ['FONASA', 'ISAPRE', 'OTRA', 'DESCONOCIDA'] as const;
export const PATIENT_REGISTRATION_MODES = ['COMPLETO', 'RAPIDO'] as const;
export const PATIENT_COMPLETENESS_STATUSES = [
  'INCOMPLETA',
  'PENDIENTE_VERIFICACION',
  'VERIFICADA',
] as const;
export const ENCOUNTER_STATUSES = ['EN_PROGRESO', 'COMPLETADO', 'FIRMADO', 'CANCELADO'] as const;
export const ENCOUNTER_REVIEW_STATUSES = [
  'NO_REQUIERE_REVISION',
  'LISTA_PARA_REVISION',
  'REVISADA_POR_MEDICO',
] as const;
export const SECTION_KEYS = [
  'IDENTIFICACION',
  'MOTIVO_CONSULTA',
  'ANAMNESIS_PROXIMA',
  'ANAMNESIS_REMOTA',
  'REVISION_SISTEMAS',
  'EXAMEN_FISICO',
  'SOSPECHA_DIAGNOSTICA',
  'TRATAMIENTO',
  'RESPUESTA_TRATAMIENTO',
  'OBSERVACIONES',
] as const;
export const CHOSEN_MODES = ['AUTO', 'MANUAL'] as const;
export const AUDIT_ACTIONS = [
  'CREATE',
  'UPDATE',
  'DELETE',
  'LOGIN',
  'LOGOUT',
  'LOGIN_FAILED',
  'PASSWORD_CHANGED',
  'READ',
  'EXPORT',
  'DOWNLOAD',
] as const;
export const AUDIT_RESULTS = ['SUCCESS', 'REJECTED', 'ERROR'] as const;
export const PATIENT_PROBLEM_STATUSES = ['ACTIVO', 'CRONICO', 'EN_ESTUDIO', 'RESUELTO'] as const;
export const ENCOUNTER_TASK_STATUSES = ['PENDIENTE', 'EN_PROCESO', 'COMPLETADA', 'CANCELADA'] as const;
export const ENCOUNTER_TASK_TYPES = ['SEGUIMIENTO', 'EXAMEN', 'DERIVACION', 'TRAMITE'] as const;
export const ENCOUNTER_TASK_PRIORITIES = ['ALTA', 'MEDIA', 'BAJA'] as const;
export const ENCOUNTER_TASK_RECURRENCE_RULES = ['NONE', 'WEEKLY', 'MONTHLY'] as const;
